language: perl

sudo: false

perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'

script:
  - perl Build.PL && ./Build && ./Build test

notifications:
  email: false
  slack:
    secure: bD7q05sALfRQ90uxBqRLjCQYzZh9+Kk9bQFiaCUGlkKlVZDwJFmAF17j2xD6E1tjBWIKEjRh/YL8jLy2Cdbgtl9TywfDfXyrk2gRznJcTwtFk9F41tL9D8ga1O7KRe605ggqagFI22jLifb6anFX4Cj1rhseQChWNu3B51bY2BU6PKOq/cI1a7IgRo814d8fsAAftPZ3D0WBbCp9vPHj4myVYV+ar9vLTtT7VIrxblBdbj2SPE0LdaPTTMcPJsmn/P9hxzkYTWjhJrPjuTileY4PNxgUW9vR0/D+YyHw+XgLCBtZcFOZvsDpMosuBkjdHFpCxrP17i9W1vM4e1bDwRAxGYXudFUUI0fkGtOBNXxTMD1DS7kcqMAAGU9UJ5Y7YfvhczTVoqVvVP/6POjsilKDJ37DCvAVNZ0D0lBSOQFkud1hBo1XX+yDOgjp1PbWqccNuBjFb3akUWHShWHICQWPBz1CUlP4SgGow8cwPrz6qC8Z76RMR6DtXorsq/JP288sy74sVzSbnZr1TQz3epNW+zt4js8w1wgQ0zNP7TybR6v5U54rhoSgEl1sZtPDKKCSl46atqHpeGfyUgHek/oBW7E4qX0zpPVIrwXtZDCMuyPgW9WFWay0o306Jer906PH0UtvOx4jJJpH4ojrNHWsMWSyU18uVMks+RCKu7k=
