language: perl
sudo: false
perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'
notifications:
  email: false
  slack:
    secure: TZP0Op1Joy5Mo7dCob101U+b2WBeZsx84uki2HFj6MVpSDWTxoRIaNNuQfjmoWgIji0zzob9BycZKd+vmJNhSf6z6IGyEDYeus3axCMbTXoDRtdy8Sg49apUiSmx2kXknEhOLgziK6qRQsxWhSvoU8YwA3/6rUth+TdVwmTqTANdK6Lwt6YkQEVsB249wwTEhQIv/yq4L9HqZ84kkMkhdOpaXtcHErhy7CvUd3gTravmJWB8jAoYTWsRrrJNTypjog813F7FHS4EJxV/oSTLvFX4D5t3q+/KJ/cVVCft1GEZpGN9Ta8Nq7D/neq7yIDUOnJAwxZpM4c8ZOikq6rS/JQeXuTkqqZQP/FGvWYlKlBH3FJJAfSDT85inejZypyiT/bXDTcGLozUvmcu345uNdWTTP2/ib+vc1Ib/qEQFVwLiDQQ936z7Kn5trJ7SeQqSWRto4nZS7mWu2uMIwgS4+3Uh/mk6gmumbFxfK7kM8ziRQKqfLCk+DdjVVrFBaB2fGs65aAE1lgRiahiplC4fILfUiPHpRj/g5iQnVpr5bN5OPp1MhCBrLDW7cDcAM7JDt6XJvGsTSJvL3MQwUc9mDcD337CHuGCCC4yOB3urm8D99LZsIYUFLtPq2aO8JZd7SDBUiKWr/pRxKlKCSUWroMWXVQoZZMbMdC3iNfD2p0=
